package ecs

// Code generated by go generate; DO NOT EDIT.

import "testing"

func TestObserve1(t *testing.T) {
	w := NewWorld()
	var obs *Observer1[CompA]
	obs = obs.New(OnAddComponents).Do(func(e Entity, a *CompA) {}).Register(w)

	expectPanicsWithValue(t, "can't modify a registered observer",
		func() {
			obs.For(C[Position]())
		})
	expectPanicsWithValue(t, "can't modify a registered observer",
		func() {
			obs.With(C[Position]())
		})
	expectPanicsWithValue(t, "can't modify a registered observer",
		func() {
			obs.Without(C[Position]())
		})
	expectPanicsWithValue(t, "can't modify a registered observer",
		func() {
			obs.Exclusive()
		})

	expectPanicsWithValue(t, "observer callback must be set via Do before registering",
		func() {
			Observe1[CompA](OnCreateEntity).Register(w)
		})
	expectPanicsWithValue(t, "observer already has a callback",
		func() {
			Observe1[CompA](OnCreateEntity).
				Do(func(e Entity, a *CompA) {}).
				Do(func(e Entity, a *CompA) {})
		})

	obs = Observe1[CompA](OnAddComponents).Do(func(e Entity, a *CompA) {})

	obs.For()
	expectEqual(t, 1, len(obs.observer.comps))

	obs.For(C[Position]())
	expectEqual(t, 1+1, len(obs.observer.comps))

	obs = Observe1[CompA](OnAddComponents).With().Do(func(e Entity, a *CompA) {}).Register(w)
	expectEqual(t, 0, len(obs.observer.with))
	expectFalse(t, obs.observer.hasWith)

	obs = Observe1[CompA](OnAddComponents).With(C[Position]()).Do(func(e Entity, a *CompA) {}).Register(w)
	expectEqual(t, 1, len(obs.observer.with))
	expectTrue(t, obs.observer.hasWith)

	obs = Observe1[CompA](OnAddComponents).Without().Do(func(e Entity, a *CompA) {}).Register(w)
	expectEqual(t, 0, len(obs.observer.without))
	expectFalse(t, obs.observer.hasWithout)

	obs = Observe1[CompA](OnAddComponents).Without(C[Position]()).Do(func(e Entity, a *CompA) {}).Register(w)
	expectEqual(t, 1, len(obs.observer.without))
	expectTrue(t, obs.observer.hasWithout)

	obs = Observe1[CompA](OnAddComponents).For(C[Position]()).Do(func(e Entity, a *CompA) {}).Register(w)
	expectEqual(t, 1+1, len(obs.observer.comps))
	expectTrue(t, obs.observer.hasComps)

	obs.Unregister(w)
	obs.Register(w)
	expectEqual(t, 1+1, len(obs.observer.comps))
	expectTrue(t, obs.observer.hasComps)
}

func TestObserver1Register(t *testing.T) {
	w := NewWorld()

	obs1 := Observe1[CompA](OnCreateEntity).
		With(C[Position]()).
		Without(C[Heading]()).
		Do(func(e Entity, a *CompA) {}).
		Register(w)
	expectTrue(t, w.storage.observers.HasObservers(OnCreateEntity))

	obs2 := Observe1[CompA](OnCreateEntity).
		With(C[Position]()).
		Do(func(e Entity, a *CompA) {}).
		Register(w)

	expectPanicsWithValue(t, "observer is already registered",
		func() {
			obs1.Register(w)
		})

	obs1.Unregister(w)
	expectTrue(t, w.storage.observers.HasObservers(OnCreateEntity))
	obs2.Unregister(w)
	expectFalse(t, w.storage.observers.HasObservers(OnCreateEntity))
}

func TestObserver1Callback(t *testing.T) {
	w := NewWorld()
	builder := NewMap1[CompA](w)

	Observe1[CompA](OnCreateEntity).
		Do(func(e Entity, a *CompA) {
			expectEqual(t, CompA{}, *a)
		}).
		Register(w)

	builder.NewEntity(
		&CompA{},
	)
}

func TestObserve2(t *testing.T) {
	w := NewWorld()
	var obs *Observer2[CompA, CompB]
	obs = obs.New(OnAddComponents).Do(func(e Entity, a *CompA, b *CompB) {}).Register(w)

	expectPanicsWithValue(t, "can't modify a registered observer",
		func() {
			obs.For(C[Position]())
		})
	expectPanicsWithValue(t, "can't modify a registered observer",
		func() {
			obs.With(C[Position]())
		})
	expectPanicsWithValue(t, "can't modify a registered observer",
		func() {
			obs.Without(C[Position]())
		})
	expectPanicsWithValue(t, "can't modify a registered observer",
		func() {
			obs.Exclusive()
		})

	expectPanicsWithValue(t, "observer callback must be set via Do before registering",
		func() {
			Observe2[CompA, CompB](OnCreateEntity).Register(w)
		})
	expectPanicsWithValue(t, "observer already has a callback",
		func() {
			Observe2[CompA, CompB](OnCreateEntity).
				Do(func(e Entity, a *CompA, b *CompB) {}).
				Do(func(e Entity, a *CompA, b *CompB) {})
		})

	obs = Observe2[CompA, CompB](OnAddComponents).Do(func(e Entity, a *CompA, b *CompB) {})

	obs.For()
	expectEqual(t, 2, len(obs.observer.comps))

	obs.For(C[Position]())
	expectEqual(t, 2+1, len(obs.observer.comps))

	obs = Observe2[CompA, CompB](OnAddComponents).With().Do(func(e Entity, a *CompA, b *CompB) {}).Register(w)
	expectEqual(t, 0, len(obs.observer.with))
	expectFalse(t, obs.observer.hasWith)

	obs = Observe2[CompA, CompB](OnAddComponents).With(C[Position]()).Do(func(e Entity, a *CompA, b *CompB) {}).Register(w)
	expectEqual(t, 1, len(obs.observer.with))
	expectTrue(t, obs.observer.hasWith)

	obs = Observe2[CompA, CompB](OnAddComponents).Without().Do(func(e Entity, a *CompA, b *CompB) {}).Register(w)
	expectEqual(t, 0, len(obs.observer.without))
	expectFalse(t, obs.observer.hasWithout)

	obs = Observe2[CompA, CompB](OnAddComponents).Without(C[Position]()).Do(func(e Entity, a *CompA, b *CompB) {}).Register(w)
	expectEqual(t, 1, len(obs.observer.without))
	expectTrue(t, obs.observer.hasWithout)

	obs = Observe2[CompA, CompB](OnAddComponents).For(C[Position]()).Do(func(e Entity, a *CompA, b *CompB) {}).Register(w)
	expectEqual(t, 2+1, len(obs.observer.comps))
	expectTrue(t, obs.observer.hasComps)

	obs.Unregister(w)
	obs.Register(w)
	expectEqual(t, 2+1, len(obs.observer.comps))
	expectTrue(t, obs.observer.hasComps)
}

func TestObserver2Register(t *testing.T) {
	w := NewWorld()

	obs1 := Observe2[CompA, CompB](OnCreateEntity).
		With(C[Position]()).
		Without(C[Heading]()).
		Do(func(e Entity, a *CompA, b *CompB) {}).
		Register(w)
	expectTrue(t, w.storage.observers.HasObservers(OnCreateEntity))

	obs2 := Observe2[CompA, CompB](OnCreateEntity).
		With(C[Position]()).
		Do(func(e Entity, a *CompA, b *CompB) {}).
		Register(w)

	expectPanicsWithValue(t, "observer is already registered",
		func() {
			obs1.Register(w)
		})

	obs1.Unregister(w)
	expectTrue(t, w.storage.observers.HasObservers(OnCreateEntity))
	obs2.Unregister(w)
	expectFalse(t, w.storage.observers.HasObservers(OnCreateEntity))
}

func TestObserver2Callback(t *testing.T) {
	w := NewWorld()
	builder := NewMap2[CompA, CompB](w)

	Observe2[CompA, CompB](OnCreateEntity).
		Do(func(e Entity, a *CompA, b *CompB) {
			expectEqual(t, CompA{}, *a)
		}).
		Register(w)

	builder.NewEntity(
		&CompA{},
		&CompB{},
	)
}

func TestObserve3(t *testing.T) {
	w := NewWorld()
	var obs *Observer3[CompA, CompB, CompC]
	obs = obs.New(OnAddComponents).Do(func(e Entity, a *CompA, b *CompB, c *CompC) {}).Register(w)

	expectPanicsWithValue(t, "can't modify a registered observer",
		func() {
			obs.For(C[Position]())
		})
	expectPanicsWithValue(t, "can't modify a registered observer",
		func() {
			obs.With(C[Position]())
		})
	expectPanicsWithValue(t, "can't modify a registered observer",
		func() {
			obs.Without(C[Position]())
		})
	expectPanicsWithValue(t, "can't modify a registered observer",
		func() {
			obs.Exclusive()
		})

	expectPanicsWithValue(t, "observer callback must be set via Do before registering",
		func() {
			Observe3[CompA, CompB, CompC](OnCreateEntity).Register(w)
		})
	expectPanicsWithValue(t, "observer already has a callback",
		func() {
			Observe3[CompA, CompB, CompC](OnCreateEntity).
				Do(func(e Entity, a *CompA, b *CompB, c *CompC) {}).
				Do(func(e Entity, a *CompA, b *CompB, c *CompC) {})
		})

	obs = Observe3[CompA, CompB, CompC](OnAddComponents).Do(func(e Entity, a *CompA, b *CompB, c *CompC) {})

	obs.For()
	expectEqual(t, 3, len(obs.observer.comps))

	obs.For(C[Position]())
	expectEqual(t, 3+1, len(obs.observer.comps))

	obs = Observe3[CompA, CompB, CompC](OnAddComponents).With().Do(func(e Entity, a *CompA, b *CompB, c *CompC) {}).Register(w)
	expectEqual(t, 0, len(obs.observer.with))
	expectFalse(t, obs.observer.hasWith)

	obs = Observe3[CompA, CompB, CompC](OnAddComponents).With(C[Position]()).Do(func(e Entity, a *CompA, b *CompB, c *CompC) {}).Register(w)
	expectEqual(t, 1, len(obs.observer.with))
	expectTrue(t, obs.observer.hasWith)

	obs = Observe3[CompA, CompB, CompC](OnAddComponents).Without().Do(func(e Entity, a *CompA, b *CompB, c *CompC) {}).Register(w)
	expectEqual(t, 0, len(obs.observer.without))
	expectFalse(t, obs.observer.hasWithout)

	obs = Observe3[CompA, CompB, CompC](OnAddComponents).Without(C[Position]()).Do(func(e Entity, a *CompA, b *CompB, c *CompC) {}).Register(w)
	expectEqual(t, 1, len(obs.observer.without))
	expectTrue(t, obs.observer.hasWithout)

	obs = Observe3[CompA, CompB, CompC](OnAddComponents).For(C[Position]()).Do(func(e Entity, a *CompA, b *CompB, c *CompC) {}).Register(w)
	expectEqual(t, 3+1, len(obs.observer.comps))
	expectTrue(t, obs.observer.hasComps)

	obs.Unregister(w)
	obs.Register(w)
	expectEqual(t, 3+1, len(obs.observer.comps))
	expectTrue(t, obs.observer.hasComps)
}

func TestObserver3Register(t *testing.T) {
	w := NewWorld()

	obs1 := Observe3[CompA, CompB, CompC](OnCreateEntity).
		With(C[Position]()).
		Without(C[Heading]()).
		Do(func(e Entity, a *CompA, b *CompB, c *CompC) {}).
		Register(w)
	expectTrue(t, w.storage.observers.HasObservers(OnCreateEntity))

	obs2 := Observe3[CompA, CompB, CompC](OnCreateEntity).
		With(C[Position]()).
		Do(func(e Entity, a *CompA, b *CompB, c *CompC) {}).
		Register(w)

	expectPanicsWithValue(t, "observer is already registered",
		func() {
			obs1.Register(w)
		})

	obs1.Unregister(w)
	expectTrue(t, w.storage.observers.HasObservers(OnCreateEntity))
	obs2.Unregister(w)
	expectFalse(t, w.storage.observers.HasObservers(OnCreateEntity))
}

func TestObserver3Callback(t *testing.T) {
	w := NewWorld()
	builder := NewMap3[CompA, CompB, CompC](w)

	Observe3[CompA, CompB, CompC](OnCreateEntity).
		Do(func(e Entity, a *CompA, b *CompB, c *CompC) {
			expectEqual(t, CompA{}, *a)
		}).
		Register(w)

	builder.NewEntity(
		&CompA{},
		&CompB{},
		&CompC{},
	)
}

func TestObserve4(t *testing.T) {
	w := NewWorld()
	var obs *Observer4[CompA, CompB, CompC, CompD]
	obs = obs.New(OnAddComponents).Do(func(e Entity, a *CompA, b *CompB, c *CompC, d *CompD) {}).Register(w)

	expectPanicsWithValue(t, "can't modify a registered observer",
		func() {
			obs.For(C[Position]())
		})
	expectPanicsWithValue(t, "can't modify a registered observer",
		func() {
			obs.With(C[Position]())
		})
	expectPanicsWithValue(t, "can't modify a registered observer",
		func() {
			obs.Without(C[Position]())
		})
	expectPanicsWithValue(t, "can't modify a registered observer",
		func() {
			obs.Exclusive()
		})

	expectPanicsWithValue(t, "observer callback must be set via Do before registering",
		func() {
			Observe4[CompA, CompB, CompC, CompD](OnCreateEntity).Register(w)
		})
	expectPanicsWithValue(t, "observer already has a callback",
		func() {
			Observe4[CompA, CompB, CompC, CompD](OnCreateEntity).
				Do(func(e Entity, a *CompA, b *CompB, c *CompC, d *CompD) {}).
				Do(func(e Entity, a *CompA, b *CompB, c *CompC, d *CompD) {})
		})

	obs = Observe4[CompA, CompB, CompC, CompD](OnAddComponents).Do(func(e Entity, a *CompA, b *CompB, c *CompC, d *CompD) {})

	obs.For()
	expectEqual(t, 4, len(obs.observer.comps))

	obs.For(C[Position]())
	expectEqual(t, 4+1, len(obs.observer.comps))

	obs = Observe4[CompA, CompB, CompC, CompD](OnAddComponents).With().Do(func(e Entity, a *CompA, b *CompB, c *CompC, d *CompD) {}).Register(w)
	expectEqual(t, 0, len(obs.observer.with))
	expectFalse(t, obs.observer.hasWith)

	obs = Observe4[CompA, CompB, CompC, CompD](OnAddComponents).With(C[Position]()).Do(func(e Entity, a *CompA, b *CompB, c *CompC, d *CompD) {}).Register(w)
	expectEqual(t, 1, len(obs.observer.with))
	expectTrue(t, obs.observer.hasWith)

	obs = Observe4[CompA, CompB, CompC, CompD](OnAddComponents).Without().Do(func(e Entity, a *CompA, b *CompB, c *CompC, d *CompD) {}).Register(w)
	expectEqual(t, 0, len(obs.observer.without))
	expectFalse(t, obs.observer.hasWithout)

	obs = Observe4[CompA, CompB, CompC, CompD](OnAddComponents).Without(C[Position]()).Do(func(e Entity, a *CompA, b *CompB, c *CompC, d *CompD) {}).Register(w)
	expectEqual(t, 1, len(obs.observer.without))
	expectTrue(t, obs.observer.hasWithout)

	obs = Observe4[CompA, CompB, CompC, CompD](OnAddComponents).For(C[Position]()).Do(func(e Entity, a *CompA, b *CompB, c *CompC, d *CompD) {}).Register(w)
	expectEqual(t, 4+1, len(obs.observer.comps))
	expectTrue(t, obs.observer.hasComps)

	obs.Unregister(w)
	obs.Register(w)
	expectEqual(t, 4+1, len(obs.observer.comps))
	expectTrue(t, obs.observer.hasComps)
}

func TestObserver4Register(t *testing.T) {
	w := NewWorld()

	obs1 := Observe4[CompA, CompB, CompC, CompD](OnCreateEntity).
		With(C[Position]()).
		Without(C[Heading]()).
		Do(func(e Entity, a *CompA, b *CompB, c *CompC, d *CompD) {}).
		Register(w)
	expectTrue(t, w.storage.observers.HasObservers(OnCreateEntity))

	obs2 := Observe4[CompA, CompB, CompC, CompD](OnCreateEntity).
		With(C[Position]()).
		Do(func(e Entity, a *CompA, b *CompB, c *CompC, d *CompD) {}).
		Register(w)

	expectPanicsWithValue(t, "observer is already registered",
		func() {
			obs1.Register(w)
		})

	obs1.Unregister(w)
	expectTrue(t, w.storage.observers.HasObservers(OnCreateEntity))
	obs2.Unregister(w)
	expectFalse(t, w.storage.observers.HasObservers(OnCreateEntity))
}

func TestObserver4Callback(t *testing.T) {
	w := NewWorld()
	builder := NewMap4[CompA, CompB, CompC, CompD](w)

	Observe4[CompA, CompB, CompC, CompD](OnCreateEntity).
		Do(func(e Entity, a *CompA, b *CompB, c *CompC, d *CompD) {
			expectEqual(t, CompA{}, *a)
		}).
		Register(w)

	builder.NewEntity(
		&CompA{},
		&CompB{},
		&CompC{},
		&CompD{},
	)
}
